/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/tim/Dropbox/Workspaces/tim-ros-pkgs/src/wifi_localization/msg/AccessPoint.msg
 *
 */


#ifndef WIFI_LOCALIZATION_MESSAGE_ACCESSPOINT_H
#define WIFI_LOCALIZATION_MESSAGE_ACCESSPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wifi_localization
{
template <class ContainerAllocator>
struct AccessPoint_
{
  typedef AccessPoint_<ContainerAllocator> Type;

  AccessPoint_()
    : mac_address()
    , ss(0)
    , noise(0)  {
    }
  AccessPoint_(const ContainerAllocator& _alloc)
    : mac_address(_alloc)
    , ss(0)
    , noise(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mac_address_type;
  _mac_address_type mac_address;

   typedef int16_t _ss_type;
  _ss_type ss;

   typedef int16_t _noise_type;
  _noise_type noise;




  typedef boost::shared_ptr< ::wifi_localization::AccessPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wifi_localization::AccessPoint_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct AccessPoint_

typedef ::wifi_localization::AccessPoint_<std::allocator<void> > AccessPoint;

typedef boost::shared_ptr< ::wifi_localization::AccessPoint > AccessPointPtr;
typedef boost::shared_ptr< ::wifi_localization::AccessPoint const> AccessPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wifi_localization::AccessPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wifi_localization::AccessPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wifi_localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wifi_localization': ['/home/tim/Dropbox/Workspaces/tim-ros-pkgs/src/wifi_localization/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wifi_localization::AccessPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wifi_localization::AccessPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wifi_localization::AccessPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wifi_localization::AccessPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_localization::AccessPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wifi_localization::AccessPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wifi_localization::AccessPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14566870ce27da9eaacf517d23cded21";
  }

  static const char* value(const ::wifi_localization::AccessPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14566870ce27da9eULL;
  static const uint64_t static_value2 = 0xaacf517d23cded21ULL;
};

template<class ContainerAllocator>
struct DataType< ::wifi_localization::AccessPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wifi_localization/AccessPoint";
  }

  static const char* value(const ::wifi_localization::AccessPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wifi_localization::AccessPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mac_address # MAC address of an access point\n\
int16 ss           # signal strength [RSSI]\n\
int16 noise        # noise\n\
\n\
";
  }

  static const char* value(const ::wifi_localization::AccessPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wifi_localization::AccessPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mac_address);
      stream.next(m.ss);
      stream.next(m.noise);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AccessPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wifi_localization::AccessPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wifi_localization::AccessPoint_<ContainerAllocator>& v)
  {
    s << indent << "mac_address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mac_address);
    s << indent << "ss: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ss);
    s << indent << "noise: ";
    Printer<int16_t>::stream(s, indent + "  ", v.noise);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIFI_LOCALIZATION_MESSAGE_ACCESSPOINT_H
